[platformio]
default_envs = esp32-s3-nano

[env:esp32-s3-nano]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  bblanchon/ArduinoJson@^7.4.2
  https://github.com/Bodmer/U8g2_for_TFT_eSPI.git#a170ef8b6d8414b1ee2ecc97b5b913e08f5597ac
build_flags =
  -D USER_SETUP_LOADED=1
  -D BOARD_HAS_PSRAM=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ST7789_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=240
  -D TFT_MOSI=11
  -D TFT_SCLK=12
  -D TFT_CS=10
  -D TFT_DC=9
  -D TFT_RST=8
  -D TFT_BL=7
  -D TFT_BACKLIGHT_ON=HIGH
  -D USE_HSPI_PORT=1
  -D SPI_FREQUENCY=40000000
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D SMOOTH_FONT=1

[env:esp32-s3-nano-jtag]
extends = env:esp32-s3-nano
upload_protocol = esp-builtin
